fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - {path: ^/api/v1/, priorities: [json], fallback_format: json, prefer_extension: false}
            - {path: ^/, priorities: [html, json, xml], fallback_format: json, prefer_extension: false}
    body_listener:
        enabled: false
