framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    csrf_protection:
        enabled: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

    templating:
        engines: ['twig', 'php']
    cache:
        app: cache.adapter.redis
        directory: '%kernel.cache_dir%/pools'
    #        default_doctrine_provider: ~
    #    default_psr6_provider: ~
        default_redis_provider: 'redis://localhost'
        default_memcached_provider: 'memcached://localhost'
        pools:
            meeting:
                adapter: cache.app
                public: false
                default_lifetime: 0
                provider: ~
                clearer: ~

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: you@example.com
        sender_name: Youk
